### ISSUE TITLE
When opening a popup inside a popup, the first close button doesn't working

### ISSUE THREAD

**Issue by diogocsc** [colorfulfool/rails-popup#5]
Hi, 
So I have this situation where it helps me to have a popup inside a popup, just to make user's life "easier". (Ideally I imagine opening a new screen inside the same popup and be able to get back to the previous popup..wonder if that's possible somehow ?)
Lets call the first popup A and the second B.
After opening B, I found three issues:

1. I'm still able to access A's content (no grey screen there)
2. Either I click close button on A or B, it's B that closes
3. After B closing, A's close button stops working

How to cope with this?

**Comment by colorfulfool** [comment]
Thanks for this chance to take a little dive into Javascript closures, the problem was indeed in them!

I've fixed the close button behavior. The backdrop issue is more of a feature request than a bug, and it's a feature not worth implementing. Modals (popups) are considered somewhat an anti-pattern in interaction design, and modals within modals, I assume, even more so.

You can do JS things to the insides of the popup in the callback:

![2017-11-08 15 35 03](https://user-images.githubusercontent.com/1292290/32549414-69df8818-c49a-11e7-89dd-93b5a8e38b63.png)
